"""removed type and resolution fields of media

Revision ID: bb364c7ec5cb
Revises: 887de3ffb5e1
Create Date: 2024-05-25 23:05:26.423192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb364c7ec5cb'
down_revision: Union[str, None] = '887de3ffb5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'resolution')
    op.drop_column('media', 'type_')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('type_', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('resolution', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
