from typing import Protocol

from src.backoffice.contexts.shared.domain.criteria import Criteria

from .content import Content


class ContentRepository(Protocol):
    def search_all(self) -> list[Content]: ...
    def search(self, id: str) -> Content | None: ...
    def matching(self, criteria: Criteria) -> list[Content]: ...
    def count(self) -> int: ...
    def save(self, beer: Content) -> None: ...
    def delete(self, id: str) -> None: ...
