[tool.poetry]
name = "media_platform"
version = "0.1.0"
description = ""
authors = ["Damian Ontivero <damian.ontivero@icloud.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
priority = "supplemental"

[tool.poetry.dependencies]
python = "^3.12"
alembic = "^1.13.1"
cryptography = "^42.0.8"
ditainer = "^0.4.10"
fastapi = "^0.111.0"
moviepy = "^1.0.3"
python-multipart = "^0.0.9"
python-dotenv = "^1.0.1"
pytest-mock = "^3.14.0"
psycopg2-binary = "^2.9.9"
sqlalchemy = "^2.0.31"
uvicorn = "^0.30.1"
werkzeug = "^3.0.3"
aio-pika = "^9.4.1"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
factory-boy = "^3.3.0"
flake8 = "^7.1.0"
ipdb = "^0.13.13"
isort = "^5.13.2"
pytest = "^8.2.2"
pytest-asyncio = "^0.23.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 120
