services:
    media_platform_api_v0:
        image: media_platform_api_v0
        build:
            context: ../../../../../../
            dockerfile: ./etc/docker/contexts/backoffice/api/v0/Dockerfile
        container_name: media_platform_api_v0
        env_file:
            - ../../../../../../.env
        environment:
            POSTGRES_HOST: media_platform_postgres
        ports:
            - "8000:8000"
        networks:
            - media_platform

networks:
    media_platform:
        name: media_platform
        external: true
