services:
  media_platform_postgres:
    extends:
      file: ./postgres/compose.yaml
      service: media_platform_postgres

  media_platform_postgres-api-v0:
    extends:
      file: ./api/v0/compose.yaml
      service: media_platform_api-v0

networks:
  media_platform:
    name: media_platform
