services:
  media_platform_postgres:
    image: postgres:16.2
    container_name: media_platform_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_platform
      POSTGRES_HOST: media_platform_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgres/data
    networks:
      - media_platform

networks:
  media_platform:
    name: media_platform
